name: Ruby

on: [push, pull_request]

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Run typecheck
        run: bundle exec srb tc
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        ruby-version: ['2.7', '3.0']

    runs-on: ${{ matrix.os }}
    env:
      BUNDLE_WITHOUT: typecheck
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run tests
      run: bundle exec rake
